/**
 * AI Suggestions Panel for displaying and applying AI-generated visualization recommendations.
 *
 * This component renders a list of visualization suggestions generated by AI (Gemini, OpenAI,
 * or Claude). Each suggestion includes:
 * - Visualization title and description
 * - Chart type and recommended variables
 * - AI reasoning explaining why this chart is valuable
 * - Confidence score (0-100%) with color-coded badge
 * - Individual apply button
 *
 * The panel handles multiple states:
 * - **Loading**: Animated spinner while AI generates suggestions
 * - **Error**: Error message with retry button
 * - **Empty**: Helpful prompt to complete wizard steps
 * - **Suggestions**: Interactive list with expand/collapse details
 *
 * Features:
 * - Expandable cards showing full reasoning on click
 * - Applied state tracking with checkmarks
 * - Bulk "Apply All" button for unapplied suggestions
 * - Applied counter in header (e.g., "5 applied")
 * - Disabled buttons for already-applied suggestions
 *
 * @module components/features/AI/AISuggestionsPanel
 */

import React, { useState } from 'react';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/common';
import {
    Sparkles,
    Plus,
    ChevronDown,
    ChevronUp,
    Check,
    Loader2,
    AlertCircle,
    RefreshCw,
    Lightbulb
} from 'lucide-react';
import { AISuggestion } from '@/types';
import { cn } from '@/lib/utils';

/**
 * Props for the AISuggestionsPanel component.
 *
 * @interface Props
 * @property {AISuggestion[]} suggestions - Array of AI-generated visualization suggestions
 * @property {boolean} isLoading - Whether AI is currently generating suggestions
 * @property {string | null} [error] - Error message if generation failed (optional)
 * @property {(suggestion: AISuggestion, index: number) => void} onApply - Callback to apply single suggestion
 * @property {() => void} onApplyAll - Callback to apply all unapplied suggestions
 * @property {() => void} [onRetry] - Optional callback to retry generation after error
 * @property {Set<number>} appliedIndices - Set of indices for already-applied suggestions
 * @property {string} [providerName] - AI provider name for loading message (optional)
 */
interface Props {
    suggestions: AISuggestion[];
    isLoading: boolean;
    error?: string | null;
    onApply: (suggestion: AISuggestion, index: number) => void;
    onApplyAll: () => void;
    onRetry?: () => void;
    appliedIndices: Set<number>;
    providerName?: string;
}

/**
 * AI Suggestions Panel component.
 *
 * Renders different UI states based on the current generation/error status:
 *
 * **Loading State**:
 * - Centered spinner with "Analyzing Your Data..." message
 * - Shows provider name if available (e.g., "Gemini is reviewing...")
 * - Displayed while waiting for AI API response
 *
 * **Error State**:
 * - Red-bordered card with error icon
 * - Displays error message from API or generic failure text
 * - "Try Again" button triggers onRetry callback
 * - Common errors: Invalid API key, quota exceeded, network issues
 *
 * **Empty State**:
 * - Lightbulb icon with friendly message
 * - Prompts user to complete previous wizard steps
 * - Only shown before first generation attempt
 *
 * **Suggestions List**:
 * - Header with suggestion count and applied count
 * - "Apply All" button (disabled if all already applied)
 * - Expandable cards for each suggestion:
 *   - **Collapsed**: Title, chart type, confidence badge, apply button
 *   - **Expanded**: Additional fields (description, variables, reasoning)
 *   - Click header to toggle expansion
 * - Applied suggestions show green checkmark instead of apply button
 * - Confidence score colors:
 *   - 80-100%: Green (high confidence)
 *   - 60-79%: Yellow (medium confidence)
 *   - <60%: Red (low confidence)
 *
 * Suggestion Card Structure:
 * - **Title**: Chart name (e.g., "Temperature vs Time")
 * - **Chart Type**: Badge showing visualization type (line, scatter, etc.)
 * - **Confidence**: Percentage badge color-coded by confidence level
 * - **Description**: (Expanded) Detailed explanation of what chart shows
 * - **Variables**: (Expanded) X-axis, Y-axis, and any calculated variables
 * - **Reasoning**: (Expanded) AI's explanation of why this chart is valuable
 * - **Action Button**: "Apply" (or checkmark if already applied)
 *
 * Interaction Patterns:
 * - Click card header: Toggles expanded/collapsed state
 * - Click "Apply": Adds visualization to dashboard, marks as applied
 * - Click "Apply All": Bulk-adds all unapplied suggestions
 * - Applied state persists until modal closes or wizard resets
 *
 * @param {Props} props - Component props
 * @returns {JSX.Element} Suggestions panel with current state
 *
 * @example
 * ```tsx
 * <AISuggestionsPanel
 *   suggestions={[
 *     {
 *       title: "Temperature Trend",
 *       description: "Shows temperature changes over time",
 *       chart_type: "line",
 *       x_axis: "Timestamp",
 *       y_axis: ["Temperature"],
 *       confidence: 0.92,
 *       reasoning: "Strong temporal correlation detected in temperature data"
 *     }
 *   ]}
 *   isLoading={false}
 *   error={null}
 *   onApply={(suggestion, index) => applySuggestion(suggestion, index)}
 *   onApplyAll={() => applyAllSuggestions()}
 *   onRetry={() => retryGeneration()}
 *   appliedIndices={new Set([0])}
 *   providerName="Gemini"
 * />
 * ```
 */
export const AISuggestionsPanel: React.FC<Props> = ({
    suggestions,
    isLoading,
    error,
    onApply,
    onApplyAll,
    onRetry,
    appliedIndices,
    providerName
}) => {
    const [expandedIndex, setExpandedIndex] = useState<number | null>(null);

    // Loading state
    if (isLoading) {
        return (
            <Card className="p-8 text-center">
                <Loader2 className="w-10 h-10 mx-auto mb-4 text-primary animate-spin" />
                <h3 className="font-semibold mb-1">Analyzing Your Data...</h3>
                <p className="text-sm text-muted-foreground">
                    {providerName ? `${providerName} is ` : 'The AI is '}
                    reviewing your column descriptions and analysis goals
                </p>
            </Card>
        );
    }

    // Error state
    if (error) {
        return (
            <Card className="p-6 border-border bg-card">
                <div className="flex items-start gap-3">
                    <AlertCircle className="w-5 h-5 text-red-500 dark:text-red-400 flex-shrink-0 mt-0.5" />
                    <div className="flex-1">
                        <h3 className="font-semibold text-foreground">AI Suggestion Failed</h3>
                        <p className="text-sm text-muted-foreground mt-1">{error}</p>
                        {onRetry && (
                            <Button
                                variant="outline"
                                size="sm"
                                onClick={onRetry}
                                className="mt-3"
                            >
                                <RefreshCw className="w-4 h-4 mr-1" />
                                Try Again
                            </Button>
                        )}
                    </div>
                </div>
            </Card>
        );
    }

    // Empty state
    if (suggestions.length === 0) {
        return (
            <Card className="p-6 text-center">
                <Lightbulb className="w-8 h-8 mx-auto mb-3 text-muted-foreground opacity-50" />
                <h3 className="font-semibold mb-1">No Suggestions Yet</h3>
                <p className="text-sm text-muted-foreground">
                    Complete the column descriptions and click "Generate Suggestions" to get AI recommendations
                </p>
            </Card>
        );
    }

    const allApplied = suggestions.every((_, i) => appliedIndices.has(i));
    const appliedCount = appliedIndices.size;

    return (
        <div className="space-y-4">
            {/* Header */}
            <div className="flex items-center justify-between">
                <h3 className="font-semibold flex items-center gap-2">
                    <Sparkles className="w-4 h-4 text-primary" />
                    AI Suggestions ({suggestions.length})
                    {appliedCount > 0 && (
                        <span className="text-xs text-muted-foreground">
                            • {appliedCount} applied
                        </span>
                    )}
                </h3>
                <Button
                    variant="outline"
                    size="sm"
                    onClick={onApplyAll}
                    disabled={allApplied}
                >
                    {allApplied ? (
                        <>
                            <Check className="w-4 h-4 mr-1" />
                            All Applied
                        </>
                    ) : (
                        <>
                            <Plus className="w-4 h-4 mr-1" />
                            Apply All
                        </>
                    )}
                </Button>
            </div>

            {/* Suggestions List */}
            <div className="space-y-2">
                {suggestions.map((suggestion, index) => {
                    const isApplied = appliedIndices.has(index);
                    const isExpanded = expandedIndex === index;

                    return (
                        <Card
                            key={index}
                            className={cn(
                                "p-4 transition-all",
                                isApplied
                                    ? "border-primary/30 bg-primary/5"
                                    : "cursor-pointer hover:border-border-prominent"
                            )}
                            onClick={() => !isApplied && setExpandedIndex(isExpanded ? null : index)}
                        >
                            <div className="flex items-start justify-between gap-3">
                                <div className="flex-1 min-w-0">
                                    {/* Title and badges */}
                                    <div className="flex items-center gap-2 flex-wrap mb-1">
                                        <h4 className="font-medium truncate">{suggestion.title}</h4>
                                        <span className="text-xs px-2 py-0.5 rounded-full bg-secondary text-secondary-foreground">
                                            {suggestion.viz_type}
                                        </span>
                                        <span
                                            className={cn(
                                                "text-xs px-2 py-0.5 rounded-full",
                                                suggestion.confidence >= 0.8
                                                    ? "bg-primary/10 text-primary"
                                                    : suggestion.confidence >= 0.5
                                                        ? "bg-muted text-muted-foreground"
                                                        : "bg-muted text-muted-foreground/70"
                                            )}
                                        >
                                            {Math.round(suggestion.confidence * 100)}% match
                                        </span>
                                    </div>

                                    {/* Description */}
                                    <p className="text-sm text-muted-foreground line-clamp-2">
                                        {suggestion.description}
                                    </p>
                                </div>

                                {/* Actions */}
                                <div className="flex items-center gap-2 shrink-0">
                                    {isApplied ? (
                                        <span className="flex items-center gap-1 text-xs font-medium text-primary bg-primary/10 px-2 py-1 rounded">
                                            <Check className="w-3 h-3" />
                                            Added
                                        </span>
                                    ) : (
                                        <>
                                            <Button
                                                variant="ghost"
                                                size="sm"
                                                onClick={(e) => {
                                                    e.stopPropagation();
                                                    onApply(suggestion, index);
                                                }}
                                                className="h-8 w-8 p-0"
                                            >
                                                <Plus className="w-4 h-4" />
                                            </Button>
                                            {isExpanded ? (
                                                <ChevronUp className="w-4 h-4 text-muted-foreground" />
                                            ) : (
                                                <ChevronDown className="w-4 h-4 text-muted-foreground" />
                                            )}
                                        </>
                                    )}
                                </div>
                            </div>

                            {/* Expanded Details */}
                            {isExpanded && !isApplied && (
                                <div className="mt-3 pt-3 border-t space-y-2 text-sm">
                                    <div className="flex flex-wrap gap-x-4 gap-y-1">
                                        <div>
                                            <span className="font-medium text-muted-foreground">X-Axis:</span>{' '}
                                            <code className="bg-muted px-1.5 py-0.5 rounded text-xs">
                                                {suggestion.x_axis}
                                            </code>
                                        </div>
                                        <div>
                                            <span className="font-medium text-muted-foreground">Y-Axis:</span>{' '}
                                            {suggestion.y_axes.map((y, i) => (
                                                <code key={i} className="bg-muted px-1.5 py-0.5 rounded text-xs mr-1">
                                                    {y}
                                                </code>
                                            ))}
                                        </div>
                                    </div>
                                    <div className="text-muted-foreground">
                                        <span className="font-medium">Reasoning:</span>{' '}
                                        <span className="italic">{suggestion.reasoning}</span>
                                    </div>
                                </div>
                            )}
                        </Card>
                    );
                })}
            </div>
        </div>
    );
};

export default AISuggestionsPanel;
